using Import3D.FBX;
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;

namespace Import3D.FBX {

    public unsafe class Utility {
        const int NumNullRecords = 25;

        char[] NULL_RECORD = new char[NumNullRecords] { // 25 null bytes in 64-bit and 13 null bytes in 32-bit
        '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0',
        '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0'
        }; // who knows why, it looks like two integers 32/64 bit (compressed and uncompressed sizes?) + 1 byte (might be compression type?)
        static string NULL_RECORD_STRING = "";// (NumNullRecords, '\0');
        char[] SEPARATOR = new char[] { '\x00', '\x01' }; // for use inside strings
        string MAGIC_NODE_TAG = "_$AssimpFbx$"; // from import
        Int64 SECOND = 46186158000; // FBX's kTime unit

        // ------------------------------------------------------------------------------------------------
        /** Get a string representation for a #TokenType. */
        string TokenTypeString(TokenType t) {
            switch (t) {
            case TokenType.TokenType_OPEN_BRACKET:
            return "TOK_OPEN_BRACKET";

            case TokenType.TokenType_CLOSE_BRACKET:
            return "TOK_CLOSE_BRACKET";

            case TokenType.TokenType_DATA:
            return "TOK_DATA";

            case TokenType.TokenType_COMMA:
            return "TOK_COMMA";

            case TokenType.TokenType_KEY:
            return "TOK_KEY";

            case TokenType.TokenType_BINARY_DATA:
            return "TOK_BINARY_DATA";
            }

            System.Diagnostics.Debug.Assert(false);
            return "";
        }

        // ------------------------------------------------------------------------------------------------
        /** Format log/error messages using a given offset in the source binary file
  *
  *  @param offset offset within the file
  *  @return A string of the following format: " (offset 0x{offset}) "*/
        string GetOffsetText(int offset) {
            //return static_cast<string>(Formatter::format() << " (offset 0x" << std::hex << offset << ") ");
            return $" (offset 0x{offset.ToString("X")}) ";
        }

        // ------------------------------------------------------------------------------------------------
        /** Format log/error messages using a given line location in the source file.
    *
    *  @param line Line index, 1-based
    *  @param column Column index, 1-based
    *  @return A string of the following format: " (line {line}, col {column}) "*/
        string GetLineAndColumnText(uint line, uint column) {
            //return static_cast<string>(Formatter::format() << " (line " << line << " <<  col " << column << ") ");
            return $" (line {line} <<  col {column}) ";
        }

        // ------------------------------------------------------------------------------------------------
        /** Format log/error messages using a given cursor token.
    *
    *  @param tok Token where parsing/processing stopped
    *  @return A string of the following format: " ({token-type}, line {line}, col {column}) "*/
        string GetTokenText(FBXToken tok) {
            if (tok.IsBinary()) {
                //return static_cast<string>(Formatter::format() << " (" << TokenTypeString(tok.Type()) << ", offset 0x" << std::hex << tok.Offset() << ") ");
                return $" ({TokenTypeString(tok.Type())}, offset 0x{tok.Offset().ToString("X")}) ";
            }

            //return static_cast<string>(Formatter::format() << " (" << TokenTypeString(tok.Type()) << ", line " << tok.Line() << ", col " << tok.Column() << ") ");
            return $" ({TokenTypeString(tok.Type())}, line {tok.Line()}, col {tok.Column()}) ";
        }

        // Generated by this formula: T["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[i]] = i;
        static byte[] base64DecodeTable = { // [128]
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
    255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 62, 255, 255, 255, 63,
    52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 255, 255, 255, 255, 255, 255,
    255, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
    15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 255, 255, 255, 255, 255,
    255, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
    41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 255, 255, 255, 255, 255
};

        /** Decode a single Base64-encoded character.
    *
    *  @param ch Character to decode (from base64 to binary).
    *  @return decoded byte value*/
        byte DecodeBase64(char ch) {
            //auto idx = static_cast<byte>(ch);
            var idx = (byte)ch;
            if (idx > 127)
                return 255;
            return base64DecodeTable[idx];
        }

        /** Compute decoded size of a Base64-encoded string
   *
   *  @param in Characters to decode.
   *  @param inLength Number of characters to decode.
   *  @return size of the decoded data (number of bytes)*/
        int ComputeDecodedSizeBase64(string inValue, int inLength) {
            if (inLength < 2) {
                return 0;
            }
            //int equals = int(inValue[inLength - 1] == '=') + int(inValue[inLength - 2] == '=');
            int equals = 0;
            if (inValue[inLength - 1] == '=') { equals++; }
            if (inValue[inLength - 2] == '=') { equals++; }
            int full_length = (inLength * 3) >> 2; // div by 4
            if (full_length < equals) {
                return 0;
            }
            return full_length - equals;
        }

        /** Decode a Base64-encoded string
   *
   *  @param in Characters to decode.
   *  @param inLength Number of characters to decode.
   *  @param out Pointer where we will store the decoded data.
   *  @param maxOutLength Size of output buffer.
   *  @return size of the decoded data (number of bytes)*/
        int DecodeBase64(string inValue, int inLength, byte* outValue, int maxOutLength) {
            throw new NotImplementedException();
            //if (maxOutLength == 0 || inLength < 2) {
            //    return 0;
            //}
            //int realLength = inLength - int(inValue[inLength - 1] == '=') - int(inValue[inLength - 2] == '=');
            //int dst_offset = 0;
            //int val = 0, valb = -8;
            //for (int src_offset = 0; src_offset < realLength && dst_offset < maxOutLength; ++src_offset) {
            //    byte table_value = DecodeBase64(inValue[src_offset]);
            //    if (table_value == 255) {
            //        return 0;
            //    }
            //    val = (val << 6) + table_value;
            //    valb += 6;
            //    if (valb >= 0) {
            //        outValue[dst_offset++] = static_cast<byte>((val >> valb) & 0xFF);
            //        valb -= 8;
            //        val &= 0xFFF;
            //    }
            //}
            //return dst_offset;
        }

        static string to_base64_string = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
        /** Encode bytes in base64-encoding
      *
      *  @param data Binary data to encode.
      *  @param inLength Number of bytes to encode.
      *  @return base64-encoded string*/
        char EncodeBase64(char _byte) {
            return to_base64_string[(int)_byte];
        }

        /** Encodes a block of 4 bytes to base64 encoding
         *
         *  @param bytes Bytes to encode.
         *  @param out_string String to write encoded values to.
         *  @param string_pos Position in out_string.*/
        void EncodeByteBlock(char* bytes, StringBuilder out_string, int string_pos) {
            char b0 = (char)((bytes[0] & 0xFC) >> 2);
            char b1 = (char)((bytes[0] & 0x03) << 4 | ((bytes[1] & 0xF0) >> 4));
            char b2 = (char)((bytes[1] & 0x0F) << 2 | ((bytes[2] & 0xC0) >> 6));
            char b3 = (char)((bytes[2] & 0x3F));

            out_string[string_pos + 0] = EncodeBase64(b0);
            out_string[string_pos + 1] = EncodeBase64(b1);
            out_string[string_pos + 2] = EncodeBase64(b2);
            out_string[string_pos + 3] = EncodeBase64(b3);
        }


        StringBuilder EncodeBase64(char* data, int length) {
            // calculate extra bytes needed to get a multiple of 3
            int extraBytes = 3 - length % 3;

            // number of base64 bytes
            int encodedBytes = 4 * (length + extraBytes) / 3;

            //string encoded_string(encodedBytes, '=');
            var encoded_string = new StringBuilder(encodedBytes);
            for (int i = 0; i < encodedBytes; i++) { encoded_string[i] = '='; }

            // read blocks of 3 bytes
            for (int ib3 = 0; ib3 < length / 3; ib3++) {
                int iByte = ib3 * 3;
                int iEncodedByte = ib3 * 4;
                char* currData = &data[iByte];

                EncodeByteBlock(currData, encoded_string, iEncodedByte);
            }

            // if size of data is not a multiple of 3, also encode the final bytes (and add zeros where needed)
            if (extraBytes > 0) {
                char[] finalBytes = { '\0', '\0', '\0', '\0' };
                //memcpy(finalBytes, &data[length - length % 3], length % 3);
                //Array.Copy(finalBytes, 0, data, length - length % 3, length % 3);
                for (int i = 0; i < length % 3; i++) {
                    data[length - length % 3 + i] = '\0';
                }

                int iEncodedByte = encodedBytes - 4;
                fixed (char* pBytes = finalBytes) {
                    EncodeByteBlock(pBytes, encoded_string, iEncodedByte);
                }

                // add '=' at the end
                for (int i = 0; i < 4 * extraBytes / 3; i++)
                    encoded_string[encodedBytes - i - 1] = '=';
            }
            return encoded_string;
        }


        // ------------------------------------------------------------------------------------------------
        void ConvertToAssimpScene(aiScene outValue, FBXDocument doc, bool removeEmptyBones) {
            FBXConverter converter = new FBXConverter(outValue, doc, removeEmptyBones);
        }

        // sanity check whether the input is ok
        static void validateAnimCurveNodes(List<FBXAnimationCurveNode> curves, bool strictMode) {
            FBXObject? target = (null);
            foreach (FBXAnimationCurveNode node in curves) {
                if (target == null) {
                    target = node.Target();
                }
                if (node.Target() != target) {
                    Log.WriteLine("Node target is null type.");
                }
                if (strictMode) {
                    System.Diagnostics.Debug.Assert(node.Target() == target);
                }
            }
        }

        static void copyBoneToSkeletonBone(aiMesh mesh, aiBone bone, aiSkeletonBone skeletonBone) {
            skeletonBone.mNumnWeights = bone.mNumWeights;
            skeletonBone.mWeights = bone.mWeights;
            skeletonBone.mOffsetMatrix = bone.mOffsetMatrix;
            skeletonBone.mMeshId = mesh;
            //# ifndef ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS
            skeletonBone.mNode = bone.mNode;
            //#endif
            skeletonBone.mParent = -1;
        }

        static aiSkeleton? createAiSkeleton(SkeletonBoneContainer sbc) {
            if (sbc.MeshArray.Count == 0 || sbc.SkeletonBoneToMeshLookup.Count == 0) {
                return null;
            }

            var skeleton = new aiSkeleton();
            foreach (var mesh in sbc.MeshArray) {
                if (sbc.SkeletonBoneToMeshLookup.TryGetValue(mesh, out var skeletonBones)) {
                    if (skeletonBones == null) {
                        continue;
                    }

                    skeleton.mNumBones = (uint)skeletonBones.Count;
                    skeleton.mBones = new aiSkeletonBone[skeleton.mNumBones];
                    int index = 0;
                    foreach (var bone in skeletonBones) {
                        skeleton.mBones[index++] = bone;
                    }
                }
            }

            return skeleton;
        }

        static string getAncestorBaseName(aiNode node) {
            string? nodeName = null;
            while (node != null && nodeName == null) {
                nodeName = node.mName;//.C_Str();
                node = node.mParent;
            }

            if (nodeName == null) {
                return "";
            }
            // could be std::string_view if c++17 available
            //return new string(nodeName, 0, length);
            return nodeName;
        }

        static void correctRootTransform(aiScene scene) {
            if (scene == null) {
                return;
            }

            if (scene.mMetaData == null) {
                return;
            }

            Int32 UpAxis = 1, UpAxisSign = 1, FrontAxis = 2, FrontAxisSign = 1, CoordAxis = 0, CoordAxisSign = 1;
            double UnitScaleFactor = 1.0;
            for (unsigned MetadataIndex = 0; MetadataIndex < scene.mMetaData.mNumProperties; ++MetadataIndex) {
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "UpAxis") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, UpAxis);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "UpAxisSign") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, UpAxisSign);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "FrontAxis") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, FrontAxis);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "FrontAxisSign") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, FrontAxisSign);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "CoordAxis") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, CoordAxis);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "CoordAxisSign") == 0) {
                    scene.mMetaData.Get<Int32>(MetadataIndex, CoordAxisSign);
                }
                if (strcmp(scene.mMetaData.mKeys[MetadataIndex].C_Str(), "UnitScaleFactor") == 0) {
                    scene.mMetaData.Get<double>(MetadataIndex, UnitScaleFactor);
                }
            }

            vec3 upVec, forwardVec, rightVec;
            upVec[UpAxis] = UpAxisSign * static_cast<float>(UnitScaleFactor);
            forwardVec[FrontAxis] = FrontAxisSign * static_cast<float>(UnitScaleFactor);
            rightVec[CoordAxis] = CoordAxisSign * (float)UnitScaleFactor;

            mat4 mat(rightVec.x, rightVec.y, rightVec.z, 0.0f,
            upVec.x, upVec.y, upVec.z, 0.0f,
            forwardVec.x, forwardVec.y, forwardVec.z, 0.0f,
            0.0f, 0.0f, 0.0f, 1.0f);
            scene.mRootNode.mTransformation *= mat;
        }

        void checkTokenCount(List<FBXToken> tok, uint expectedCount) {
            System.Diagnostics.Debug.Assert(expectedCount >= 2);
            if (tok.Count < expectedCount) {
                string &s = ParseTokenAsString(*tok[1]);
                if (tok[1].IsBinary()) {
                    throw DeadlyImportError("Not enough tokens for property of type ", s, " at offset ", tok[1].Offset());
                }
                else {
                    throw DeadlyImportError("Not enough tokens for property of type ", s, " at line ", tok[1].Line());
                }
            }
        }

        // ------------------------------------------------------------------------------------------------
        // read a typed property out of a FBX element. The return value is null if the property cannot be read.
        FBXProperty* ReadTypedProperty(FBXElement element) {
            System.Diagnostics.Debug.Assert(element.KeyToken().StringContents() == "P");

            List<FBXToken> tok = element.Tokens();
            if (tok.Count < 2) {
                return null;
            }

            string &s = ParseTokenAsString(*tok[1]);
            char* cs = s.c_str();
            if (!strcmp(cs, "KString")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<string>(ParseTokenAsString(*tok[4]));
            }
            else if (!strcmp(cs, "bool") || !strcmp(cs, "Bool")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<bool>(ParseTokenAsInt(*tok[4]) != 0);
            }
            else if (!strcmp(cs, "int") || !strcmp(cs, "Int") || !strcmp(cs, "enum") || !strcmp(cs, "Enum") || !strcmp(cs, "Integer")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<int>(ParseTokenAsInt(*tok[4]));
            }
            else if (!strcmp(cs, "ULongLong")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<UInt64>(ParseTokenAsID(*tok[4]));
            }
            else if (!strcmp(cs, "KTime")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<Int64>(ParseTokenAsInt64(*tok[4]));
            }
            else if (!strcmp(cs, "Vector3D") ||
                       !strcmp(cs, "ColorRGB") ||
                       !strcmp(cs, "Vector") ||
                       !strcmp(cs, "Color") ||
                       !strcmp(cs, "Lcl Translation") ||
                       !strcmp(cs, "Lcl Rotation") ||
                       !strcmp(cs, "Lcl Scaling")) {
                checkTokenCount(tok, 7);
                return new TypedProperty<vec3>(vec3(
                        ParseTokenAsFloat(*tok[4]),
                        ParseTokenAsFloat(*tok[5]),
                        ParseTokenAsFloat(*tok[6])));
            }
            else if (!strcmp(cs, "double") || !strcmp(cs, "Number") || !strcmp(cs, "float") || !strcmp(cs, "Float") || !strcmp(cs, "FieldOfView") || !strcmp(cs, "UnitScaleFactor")) {
                checkTokenCount(tok, 5);
                return new TypedProperty<float>(ParseTokenAsFloat(*tok[4]));
            }
            else if (!strcmp(cs, "ColorAndAlpha")) {
                checkTokenCount(tok, 8);
                return new TypedProperty<vec4>(vec4(
                        ParseTokenAsFloat(*tok[4]),
                        ParseTokenAsFloat(*tok[5]),
                        ParseTokenAsFloat(*tok[6]),
                        ParseTokenAsFloat(*tok[7])));
            }
            return null;
        }


        // ------------------------------------------------------------------------------------------------
        // peek into an element and check if it contains a FBX property, if so return its name.
        string PeekPropertyName(FBXElement element) {
            System.Diagnostics.Debug.Assert(element.KeyToken().StringContents() == "P");

            List<FBXToken> tok = element.Tokens();
            if (tok.Count < 4) {
                return string();
            }

            return ParseTokenAsString(*tok[0]);
        }


        public static T SafeParse<T>(byte* data, byte* end) where T : struct {
            // Actual size validation happens during Tokenization so
            // this is valid as an assertion.
            //(void)(end);
            //System.Diagnostics.Debug.Assert(static_cast<int>(end - data) >= sizeof(T));
            //T result = static_cast<T>(0);
            //memcpy(&result, data, sizeof(T));

            var span = new Span<byte>(data, (int)(end - data + 1));
            var result = MemoryMarshal.Read<T>(span);
            return result;
        }

        // ------------------------------------------------------------------------------------------------
        // Lengthy utility function to read and resolve a FBX vertex data array - that is, the
        // output is in polygon vertex order. This logic is used for reading normals, UVs, colors,
        // tangents ..
        template<typename T>
void ResolveVertexDataArray(List<T> &data_out, FBXScope source,
        string &MappingInformationType,
        string &ReferenceInformationType,
        char* dataElementName,
        char* indexDataElementName,
        int vertex_count,
        List<uint> &mapping_counts,
        List<uint> &mapping_offsets,
        List<uint> &mappings) {
            bool isDirect = ReferenceInformationType == "Direct";
            bool isIndexToDirect = ReferenceInformationType == "IndexToDirect";
            bool hasDataElement = HasElement(source, dataElementName);
            bool hasIndexDataElement = HasElement(source, indexDataElementName);

            // fall-back to direct data if there is no index data element
            if (isIndexToDirect && !hasIndexDataElement) {
                isDirect = true;
                isIndexToDirect = false;
            }

            // handle permutations of Mapping and Reference type - it would be nice to
            // deal with this more elegantly and with less redundancy, but right
            // now it seems unavoidable.
            if (MappingInformationType == "ByVertice" && isDirect) {
                if (!hasDataElement) {
                    FBXImporter::LogWarn("missing data element: ", dataElementName);
                    return;
                }
                List<T> tempData;
                ParseVectorDataArray(tempData, GetRequiredElement(source, dataElementName));

                if (tempData.Count != mapping_offsets.Count) {
                    FBXImporter::LogError("length of input data unexpected for ByVertice mapping: ",
                            tempData.Count, ", expected ", mapping_offsets.Count);
                    return;
                }

                data_out.resize(vertex_count);
                for (int i = 0, e = tempData.Count; i < e; ++i) {
                    uint istart = mapping_offsets[i], iend = istart + mapping_counts[i];
                    for (uint j = istart; j < iend; ++j) {
                        data_out[mappings[j]] = tempData[i];
                    }
                }
            }
            else if (MappingInformationType == "ByVertice" && isIndexToDirect) {
                List<T> tempData;
                if (!hasDataElement || !hasIndexDataElement) {
                    if (!hasDataElement)
                        FBXImporter::LogWarn("missing data element: ", dataElementName);
                    if (!hasIndexDataElement)
                        FBXImporter::LogWarn("missing index data element: ", indexDataElementName);
                    return;
                }

                ParseVectorDataArray(tempData, GetRequiredElement(source, dataElementName));

                List<int> uvIndices;
                ParseVectorDataArray(uvIndices, GetRequiredElement(source, indexDataElementName));

                if (uvIndices.Count != mapping_offsets.Count) {
                    FBXImporter::LogError("length of input data unexpected for ByVertice mapping: ",
                            uvIndices.Count, ", expected ", mapping_offsets.Count);
                    return;
                }

                data_out.resize(vertex_count);

                for (int i = 0, e = uvIndices.Count; i < e; ++i) {

                    uint istart = mapping_offsets[i], iend = istart + mapping_counts[i];
                    for (uint j = istart; j < iend; ++j) {
                        if (static_cast<int>(uvIndices[i]) >= tempData.Count) {
                            DOMError("index out of range", &GetRequiredElement(source, indexDataElementName));
                        }
                        data_out[mappings[j]] = tempData[uvIndices[i]];
                    }
                }
            }
            else if (MappingInformationType == "ByPolygonVertex" && isDirect) {
                if (!hasDataElement) {
                    FBXImporter::LogWarn("missing data element: ", dataElementName);
                    return;
                }

                List<T> tempData;
                ParseVectorDataArray(tempData, GetRequiredElement(source, dataElementName));

                if (tempData.Count != vertex_count) {
                    FBXImporter::LogError("length of input data unexpected for ByPolygon mapping: ",
                            tempData.Count, ", expected ", vertex_count);
                    return;
                }

                data_out.swap(tempData);
            }
            else if (MappingInformationType == "ByPolygonVertex" && isIndexToDirect) {
                List<T> tempData;
                if (!hasDataElement || !hasIndexDataElement) {
                    if (!hasDataElement)
                        FBXImporter::LogWarn("missing data element: ", dataElementName);
                    if (!hasIndexDataElement)
                        FBXImporter::LogWarn("missing index data element: ", indexDataElementName);
                    return;
                }
                ParseVectorDataArray(tempData, GetRequiredElement(source, dataElementName));

                List<int> uvIndices;
                ParseVectorDataArray(uvIndices, GetRequiredElement(source, indexDataElementName));

                if (uvIndices.Count > vertex_count) {
                    FBXImporter::LogWarn("trimming length of input array for ByPolygonVertex mapping: ",
                            uvIndices.Count, ", expected ", vertex_count);
                    uvIndices.resize(vertex_count);
                }

                if (uvIndices.Count != vertex_count) {
                    FBXImporter::LogError("length of input data unexpected for ByPolygonVertex mapping: ",
                            uvIndices.Count, ", expected ", vertex_count);
                    return;
                }

                data_out.resize(vertex_count);

                T empty;
                uint next = 0;
                for (int i : uvIndices) {
                    if (-1 == i) {
                        data_out[next++] = empty;
                        continue;
                    }
                    if (static_cast<int>(i) >= tempData.Count) {
                        DOMError("index out of range", &GetRequiredElement(source, indexDataElementName));
                    }

                    data_out[next++] = tempData[i];
                }
            }
            else {
                FBXImporter::LogError("ignoring vertex data channel, access type not implemented: ",
                        MappingInformationType, ",", ReferenceInformationType);
            }
        }

        string EXPORT_VERSION_STR = "7.5.0";
        UInt32 EXPORT_VERSION_INT = 7500; // 7.5 == 2016+
                                          // FBX files have some hashed values that depend on the creation time field,
                                          // but for now we don't actually know how to generate these.
                                          // what we can do is set them to a known-working version.
                                          // this is the data that Blender uses in their FBX export process.
        string GENERIC_CTIME = "1970-01-01 10:00:00:000";
        string GENERIC_FILEID =
                "\x28\xb3\x2a\xeb\xb6\x24\xcc\xc2\xbf\xc8\xb0\x2a\xa9\x2b\xfc\xf1";
        string GENERIC_FOOTID =
                "\xfa\xbc\xab\x09\xd0\xc8\xd4\x66\xb1\x76\xfb\x83\x1c\xf7\x26\x7e";
        string FOOT_MAGIC =
                "\xf8\x5a\x8c\x6a\xde\xf5\xd9\x7e\xec\xe9\x0c\xe3\x75\x8f\x29\x0b";
        string COMMENT_UNDERLINE =
                ";------------------------------------------------------------------";


        public static T ProcessSimpleConnection<T>(FBXConnection con,
        bool is_object_property_conn,
        char* name,
        FBXElement element,
        char** propNameOut = null) {
            if (is_object_property_conn && !con.PropertyName().length()) {
                DOMWarning("expected incoming " + string(name) +
                                   " link to be an object-object connection, ignoring",
                        &element);
                return null;
            }
            else if (!is_object_property_conn && con.PropertyName().length()) {
                DOMWarning("expected incoming " + string(name) +
                                   " link to be an object-property connection, ignoring",
                        &element);
                return null;
            }

            if (is_object_property_conn && propNameOut) {
                // note: this is ok, the return value of PropertyValue() is guaranteed to
                // remain valid and unchanged as long as the document exists.
                *propNameOut = con.PropertyName().c_str();
            }

            FBXObject* ob = con.SourceObject();
            if (!ob) {
                DOMWarning("failed to read source object for incoming " + string(name) +
                                   " link, ignoring",
                        &element);
                return null;
            }

            return dynamic_cast<T*>(ob);
        }


        // fetch a property table and the corresponding property template
        public static PropertyTable GetPropertyTable(FBXDocument doc,
                string templateName,
                FBXElement element,
                FBXScope sc,
                bool no_warn = false) {
            FBXElement* Properties70 = sc["Properties70"];
            (PropertyTable)templateProps = (PropertyTable)(static_cast<PropertyTable*>(null));

            if (templateName.length()) {
                Dictionary<string, PropertyTable>::const_iterator it = doc.Templates().find(templateName);
                if (it != doc.Templates().end()) {
                    templateProps = (*it).second;
                }
            }

            if (!Properties70 || !Properties70.Compound()) {
                if (!no_warn) {
                    DOMWarning("property table (Properties70) not found", &element);
                }
                if (templateProps) {
                    return templateProps;
                }
                else {
                    return std::make_shared<PropertyTable>();
                }
            }
            return std::make_shared<PropertyTable>(*Properties70, templateProps);
        }


        // signal DOM construction error, this is always unrecoverable. Throws new Exception.
        public static void DOMError(string message, FBXToken token) {
            throw new Exception($"FBX-DOM {token} : {message}");
        }

        // ------------------------------------------------------------------------------------------------
        public static void DOMError(string message, FBXElement? element = null) {
            if (element != null) {
                DOMError(message, element.KeyToken());
            }
            throw new Exception($"FBX-DOM {message}");
        }

        // ------------------------------------------------------------------------------------------------
        // print warning, do return
        public static void DOMWarning(string message, FBXToken token) {
            //if (DefaultLogger::get()) {
            //    ASSIMP_LOG_WARN("FBX-DOM", Util::GetTokenText(&token), message);
            //}
        }

        // ------------------------------------------------------------------------------------------------
        public static void DOMWarning(string message, FBXElement? element = null) {
            //if (element) {
            //    Utility.DOMWarning(message, element.KeyToken());
            //    return;
            //}
            //if (DefaultLogger::get()) {
            //    ASSIMP_LOG_WARN("FBX-DOM: ", message);
            //}
        }

    }
}
